FROM nginx
RUN apt-get update -qq && apt-get -y install apache2-utils
ENV RAILS_ROOT /var/www/my-shrtbrd/
RUN mkdir -p $RAILS_ROOT
WORKDIR $RAILS_ROOT
COPY config/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD [ "nginx", "-g", "daemon off;" ]