version: '3'
services:
    web:
        build:
          context: .
          dockerfile: Dockerfile.Nginx
        links:
          - app
        ports:
          - "80:80"
    db:
        image: postgres:9.3
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    app:
        build: .
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        volumes:
            - /var/www/my-shrtbrd
        ports:
            - "3000:3000"
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - RAKE_ENV= development
        depends_on:
            - db